name: system_idle
description: A sample command-line application.
version: 1.2.0
repository: https://github.com/unitedideasco/system_idle
publish_to: none

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  very_good_analysis: ^6.0.0
